[package]
name = "bomberman"
version = "0.1.0"
authors = []
edition = "2018"

[workspace]
members = ["engine"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
rand = "0.7.2"
engine = { path = "engine" }
itertools = "0.8.2"