[package]
name = "codegen"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
texture_packer = "0.17.0"
regex = "1.3.1"
lazy_static = "1.4.0"
image = "0.22.3"
serde = { version = "1.0.99", features = ["derive"] }
inflections = "1.1.1"